layout_spectrum: 0.02550512459129095
typography_spectrum: 0.48154037445783615
color:
  brandStrength: 0.921049827709794
  lightness: 0.45961531321518123
  saturation: 0.021436612587422132
  rhythmicContrast: 0.3892731540836394
  brandColors:
    - '#9FC0C6'
    - '#554D4C'
    - '#FFFFFF'
    - '#A9283C'
    - '#818D90'
author:
  name: Glenn Bolton
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/668e9397-fc81-4806-b497-5d7cf40acef4.jpg
name: The Production Exchange
title: The Production Exchange
description: 'We plan it, we deliver it, we make it happen'
