typography_spectrum: 0.48154037445783615
color:
  brandStrength: 0.921049827709794
  lightness: 0.45961531321518123
  saturation: 0.021436612587422132
  rhythmicContrast: 0.3892731540836394
  brandColors:
    - '#9FC0C6'
    - '#554D4C'
    - '#FFFFFF'
    - '#A9283C'
    - '#818D90'
layout_spectrum: 0.02550512459129095
author:
  name: Glenn Bolton
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/668e9397-fc81-4806-b497-5d7cf40acef4.jpg
name: The Production Exchange
navigation:
  - name: Event production - its what we do
    id: 2bf98123-4734-456c-99ba-d1d93e612a08
    type: content
  - name: How we do it
    id: ff9d217d-7313-46a7-bf4f-4cc648274545
    type: content
  - name: What we’re about
    id: 2f941381-e20f-494d-b67c-8ab583ca2cd2
    type: content
  - name: Services we offer
    id: 288771ec-23e6-47af-b659-f5155b888e8f
    type: content
  - name: Insight
    id: 29c7b4a7-5cad-4b44-8c10-e88801e3e768
    type: content
title: The Production Exchange
description: 'We plan it, we deliver it, we make it happen'
